# 配置服务器端口
server:
  port: 8890

spring:
  mail:
    host: ---
    username: ---
    password: ---
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  application:
    name: mail-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: iot     #设置集群名称
        ephemeral: true       #临时实例
